export const DATA_FILES = [
    { name: 'tbilisi_stops_en.json', category: 'base', source: 'tbilisi', locale: 'en' },
    { name: 'tbilisi_stops_ka.json', category: 'base', source: 'tbilisi', locale: 'ka' },
    { name: 'tbilisi_routes_en.json', category: 'base', source: 'tbilisi', locale: 'en' },
    { name: 'tbilisi_routes_ka.json', category: 'base', source: 'tbilisi', locale: 'ka' },
    { name: 'tbilisi_routes_details_en.json', category: 'base', source: 'tbilisi', locale: 'en' },
    { name: 'tbilisi_routes_details_ka.json', category: 'base', source: 'tbilisi', locale: 'ka' },
    { name: 'tbilisi_polylines.json', category: 'base', source: 'tbilisi' },
    { name: 'tbilisi_schedules.json', category: 'base', source: 'tbilisi' },

    { name: 'rustavi_stops_en.json', category: 'base', source: 'rustavi', locale: 'en' },
    { name: 'rustavi_stops_ka.json', category: 'base', source: 'rustavi', locale: 'ka' },
    { name: 'rustavi_routes_en.json', category: 'base', source: 'rustavi', locale: 'en' },
    { name: 'rustavi_routes_ka.json', category: 'base', source: 'rustavi', locale: 'ka' },
    { name: 'rustavi_routes_details_en.json', category: 'base', source: 'rustavi', locale: 'en' },
    { name: 'rustavi_routes_details_ka.json', category: 'base', source: 'rustavi', locale: 'ka' },
    { name: 'rustavi_polylines.json', category: 'base', source: 'rustavi' },
    { name: 'rustavi_schedules.json', category: 'base', source: 'rustavi' },

    { name: 'kutaisi_stops_en.json', category: 'base', source: 'kutaisi', locale: 'en' },
    { name: 'kutaisi_stops_ka.json', category: 'base', source: 'kutaisi', locale: 'ka' },
    { name: 'kutaisi_routes_en.json', category: 'base', source: 'kutaisi', locale: 'en' },
    { name: 'kutaisi_routes_ka.json', category: 'base', source: 'kutaisi', locale: 'ka' },
    { name: 'kutaisi_routes_details_en.json', category: 'base', source: 'kutaisi', locale: 'en' },
    { name: 'kutaisi_routes_details_ka.json', category: 'base', source: 'kutaisi', locale: 'ka' },
    { name: 'kutaisi_polylines.json', category: 'base', source: 'kutaisi' },
    { name: 'kutaisi_schedules.json', category: 'base', source: 'kutaisi' },

    { name: 'batumi_stops_en.json', category: 'base', source: 'batumi', locale: 'en' },
    { name: 'batumi_stops_ka.json', category: 'base', source: 'batumi', locale: 'ka' },
    { name: 'batumi_routes_en.json', category: 'base', source: 'batumi', locale: 'en' },
    { name: 'batumi_routes_ka.json', category: 'base', source: 'batumi', locale: 'ka' },
    { name: 'batumi_routes_details_en.json', category: 'base', source: 'batumi', locale: 'en' },
    { name: 'batumi_routes_details_ka.json', category: 'base', source: 'batumi', locale: 'ka' },
    { name: 'batumi_polylines.json', category: 'base', source: 'batumi' },
    { name: 'batumi_schedules.json', category: 'base', source: 'batumi' },

    { name: 'routes_overrides.csv', category: 'corrections' },
    { name: 'stops_overrides.csv', category: 'corrections' },
    { name: 'fares.csv', category: 'corrections' },
    { name: 'route_intervals.json', category: 'base' },
    { name: 'long_segments.geojson', category: 'base' },
    { name: 'metro_exits.json', category: 'base' },
    { name: 'metro_midpoints.json', category: 'base' },
    { name: 'metro_segments.json', category: 'base' },
    { name: 'metro_shapes.geojson', category: 'base' }
];
